about/urls.py
from django.urls import path
from .views import About, cv

app_name="about"
urlpatterns = [
	path('', About.as_view(), name='about'),
	path('cv/', cv, name='cv'),
]

account/urls.py
from django.urls import path

app_name='account'
urlpatterns=[]

base/urls.py
from django.urls import path
from .views import home, ContactSuccessView

app_name ="base"
urlpatterns = [
	path('', home, name="home"),
	path('success/', ContactSuccessView.as_view(), name="success"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('account/', include('account.urls')),
    path('projects/', include('projects.urls')),
    path('skills/', include('skills.urls')),
    path('about/', include('about.urls')),
)

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from .views import ProjectList, ProjectDetail, BackendLanguages

app_name= 'projects'
urlpatterns = [
	path('', ProjectList.as_view(), name='ProjectList'),
	path('detail/<slug:slug>', ProjectDetail.as_view(), name='ProjectDetail'),
	path('backend_projects/<slug:slug>', BackendLanguages.as_view(), name="backend_languages")
]

skills/urls.py
from django.urls import path
from .views import SkillList

app_name="skills"
urlpatterns = [
	path('', SkillList.as_view(), name='SkillList')
]

about/models.py
from django.db import models 
from django.utils.html import format_html
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class About(models.Model):
	name 			= models.CharField(max_length=200)
	pictuer 		= models.ImageField(upload_to="my_pictuer")
	job 			= models.CharField(max_length=30)
	about_my_self 	= models.TextField()

	def show_pictuer(self):
		return format_html('<img style="width:100px; height: 100px; border-radius:50%;" src="{}">'.format(self.pictuer.url))

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
	pass

base/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class contact(models.Model):
	address 		= models.CharField(max_length=500)
	phone_number 	= PhoneNumberField() 
	email  			= models.EmailField(max_length=200)
	my_id 			= models.IntegerField(help_text='to show the model in the page please take the my_id to 1')

projects/models.py
from django.db import models
from django.utils import timezone

# my manager
class ProjectManager(models.Manager):
	def published(self):
		return self.filter(statuc='p')

# Create your models here.
class Project(models.Model):
	STATUS_CHOICES = (
		('d' , 'Draft'),
		('p' , 'publish'),
	)
	LANGUAGE_CHOICES = (
		('p', 'python'),
		('d', 'django'),
		('c', 'css'),
		('h', 'html'),
		('b', 'bootstrap'),
		('j', 'javascript'),
	)
	title  		    = models.CharField(max_length=200)
	is_private 		= models.BooleanField(default=False)
	slug            = models.SlugField(unique=True, max_length=100)
	description     = models.TextField()
	language_type   = models.CharField(max_length=1, choices=LANGUAGE_CHOICES)
	thumbnail 	    = models.ImageField(upload_to='images')
	html_code 	    = models.TextField(null=True, blank=True)
	css_code 	    = models.TextField(null=True, blank=True)
	javascript_code = models.TextField(null=True, blank=True)
	publish  		= models.DateTimeField(default=timezone.now)
	created  		= models.DateTimeField(auto_now_add=True)
	updated  		= models.DateTimeField(auto_now=True)
	# Project 		= models.FileField(upload_to="projects", null=True, blank=True)
	downlaod_link   = models.URLField(null=True)
	statuc			= models.CharField(max_length=1, choices=STATUS_CHOICES)


	def __str__(self):
		return self.title

	objects = ProjectManager()

skills/models.py
from django.db import models

# Create your models here.
class Skill(models.Model):
	title = models.CharField(max_length=200, help_text="This title will be show on the top of the card and also in the button")
	learn_presentage = models.IntegerField(null=True)
	logo = models.CharField(max_length=500, null=True, help_text="This is an important field, in this project only font (fontawesome) is used, so according to your skill, find a suitable icon from fontawesome and enter it, for example: <i class='fa-brands fa-html5'></i>")
	description = models.TextField(null=True)
	bg_color = models.CharField(max_length=200, null=True, help_text="This field is for the background color, as in the following example: linear-gradient(45deg, #56f58d, #00ff04);")

	def __str__(self):
		return self.title 

base/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.utils.translation import gettext_lazy as _

# contact/forms.py
class ContactForm(forms.Form):


    name = forms.CharField(max_length=200)
    email = forms.EmailField()
    inquiry = forms.CharField(max_length=70)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'placeholder': _('Enter Your Name')})
        self.fields['email'].widget.attrs.update({'placeholder': _('Enter Your Email Address')})
        self.fields['inquiry'].widget.attrs.update({'placeholder': _('Inquiry')})
        self.fields['message'].widget.attrs.update({'placeholder': _('Enter Your Message')})

    def get_info(self):
        """
        Method that returns formatted information
        :return: subject, msg
        """
        # Cleaned data
        cl_data = super().clean()

        name = cl_data.get('name').strip()
        from_email = cl_data.get('email')
        subject = cl_data.get('inquiry')

        msg = f'{name} with email {from_email} said:'
        msg += f'\n"{subject}"\n\n'
        msg += cl_data.get('message')

        return subject, msg

    def send(self):

        subject, msg = self.get_info()

        send_mail(
            subject=subject,
            message=msg,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS]
        )

about/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import About

# Create your views here.

class About (ListView):
	model = About
	context_object_name = 'about_list'

def cv(request):
	return render(request, 'about/cv.html')

account/views.py
from django.shortcuts import render

# Create your views here.

base/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, FormView, TemplateView
from projects.models import Project
from skills.models import Skill
from about.models import About
from .models import contact
from .forms import ContactForm
from django.urls import reverse_lazy
from .models import contact
from django.http import HttpResponseRedirect


# Create your views here.
def home (request):

	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			form.send()
			return redirect('base:success')
	else:
		form = ContactForm()
	context = {
		'projec_list' : Project.objects.published()[:6],
		'skill_list'  : Skill.objects.all(),
		'about_list'  : About.objects.all(),
		'contact' 	  : contact,
		'form'  	  : ContactForm
	}

	return render(request, 'base/home.html', context)



class ContactSuccessView(TemplateView):
	template_name = 'contact/success.html'

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Project
from django.http import HttpResponse




# Create your views here.
class ProjectList(ListView):
	queryset = Project.objects.published()
	context_object_name = 'projec_list'


class ProjectDetail(DetailView):
	def get_object(self):
		slug = self.kwargs.get('slug')
		return get_object_or_404(Project.objects.published(), slug=slug)



class BackendLanguages(DetailView):
	template_name = 'projects/backends_language.html'
	
	def get_object(self):
		global project
		slug = self.kwargs.get('slug')
		project = get_object_or_404(Project.objects.published(), slug=slug)
		return project 

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['downlaod_link'] = project.downlaod_link
		return context

skills/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Skill

# Create your views here.
class SkillList(ListView):
	model = Skill
	context_object_name = 'skill_list'

templates/about/about_list.html
{% extends 'base/base.html' %}
{% block main %}
	{% include 'about/list.html' %}
{% endblock %}

templates/about/cv.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{% static 'cv_styles/style.css' %}">
	<title>My_Cv</title>
</head>
<body>
	<div class="wrapper">
		<div class="left">
			<div class="per">
				<div class="per-img" style="background-image: url({% static 'cv_styles/per.jpg' %});"></div>
				<h1 class="per-name">Nasir Ahmad Ahmady</h1>
				<div class="pre-job">Web Developer</div>
			</div>
			<hr>
			<div class="contact-info">
				<h1 class="contact-title">contact info</h1>
				<div class="phone"><i class="fa fa-phone" aria-hidden="true"></i>+55 11 95340 6836</div>
				<div class="email"><i class='fa fa-envelope-o' aria-hidden="true"></i>nasirahmadahmady0@gmail.com</div>				
				<div class="internet"><i class='fa fa-globe' aria-hidden="true"></i><a href="nasir1.pythonanywhere.com" style="color: #fff;">mysite</a></div>				
				<div class="linekdin"><i class='fa fa-linkedin' aria-hidden="true"></i><a style="color: #fff;" target="_blank" href="https://www.linkedin.com/in/nasir-ahmad-ahmady-4653b524a">My linkedin Account</a></div>				
				<div class="location"><i class='fa fa-map-marker' aria-hidden="true"></i>Brazil, sao paulo</div>				
			</div>
			<div class="education">
				<div class="edu">
					<div class="year">2020-at now</div>
					<div class="work">Pytho programming</div>
	    			<div class="part">programming</div>
	    			<div class="uni-name">IRANIAN YOUTUBE CHANNEL</div>
	    		</div>
	    		<div class="edu">
					<div class="year">2021-at now</div>
					<div class="work">django programming</div>
	    			<div class="part">programming</div>
	    			<div class="uni-name">IRANIAN YOUTUBE CHANNEL</div>
	    		</div>
	    		<div class="edu">
					<div class="year">2021-at now</div>
					<div class="work">HTML5, CSS3</div>
	    			<div class="part">WebDesign</div>
	    			<div class="uni-name">IRANIAN YOUTUBE CHANNEL</div>
	    		</div>
	    		<div class="edu">
					<div class="year">2021-at now</div>
					<div class="work">JavaScript programming</div>
	    			<div class="part">programming</div>
	    			<div class="uni-name">IRANIAN YOUTUBE CHANNEL</div>
	    		</div>
	    		<div class="edu">
					<div class="year">2021-at now</div>
					<div class="work">Bootstrap</div>
	    			<div class="part">WebDesign</div>
	    			<div class="uni-name">IRANIAN YOUTUBE CHANNEL</div>
	    		</div>
			</div>
			<div class="lang-wrapper">
				<h1 class="title">languages</h1>
				<div class="lang">
					<p class="title">persio</p>
					<div class="show" style="--per:100%;">
						<div class="line"></div>
					</div>
				</div>
				<div class="lang">
					<p class="title">Portugueses</p>
					<div class="show" style="--per:10%;">
						<div class="line"></div>
					</div>
				</div>
				<div class="lang">
					<p class="title">english</p>
					<div class="show" style="--per:30%;">
						<div class="line"></div>
					</div>
				</div>
				<div class="lang">
					<p class="title">Pashto</p>
					<div class="show" style="--per:60%;">
						<div class="line"></div>
					</div>
				</div>
			</div>
		</div>
		<div class="right">
			<div class="profile">
				<h1 class="title">profile</h1>
				<p class="content">
					Hello, my name is Nasir Ahmad Ahmady, I am from Afghanistan, I was born in 2004, I was interested in computers since the beginning of my life, but in 2020, I officially started programming, I started with Python language. I started programming with python because the language is simple and at the same time very powerful and I have been programming with Python for two years, later I started working with Django and I did several projects in Afghanistan,
					<br>
					such as without html, css, web world. It doesn't make sense. I started working with these two languages and later I started working with javascript and bootstrap and I have been working on the frontend side for a year.
				</p>
			</div>
			<div class="expreience">
				<h1 class="title">experience</h1>
				<div class="exp-wrapper">
					<div class="exp">
						<div class="left"><div>2020-2020</div>company name</div>
						<div class="right"><p class="title">senior ux designer</p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium quia inventore excepturi officia quasi, maxime porro tenetur ea. Quaerat qui quod, doloribus quas illum tempora minus, minima. Maxime, cupiditate, </div>
					</div>
					<div class="exp">
						<div class="left"><div>2019-present</div>company name</div>
						<div class="right"><p class="title">senior ux designer</p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium quia inventore excepturi officia quasi, maxime porro tenetur ea. Quaerat qui quod, doloribus quas illum tempora minus, minima. Maxime, cupiditate, </div>
					</div>
					<div class="exp">
						<div class="left"><div>2019-present</div>company name</div>
						<div class="right"><p class="title">senior ux designer</p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium quia inventore excepturi officia quasi, maxime porro tenetur ea. Quaerat qui quod, doloribus quas illum tempora minus, minima. Maxime, cupiditate, </div>
					</div>
				</div>
			</div>
			<div class="skills">
				<h1 class="title">professional skills</h1>
				<div class="skill-wrapper">
					<div class="skill">
						<div class="name">html</div>
						<div class="show" style="--per: 90%;"><div class="line"></div></div>
					</div>
					<div class="skill">
						<div class="name">css</div>
						<div class="show" style="--per: 80%;"><div class="line"></div></div>
					</div><div class="skill">
						<div class="name">javascript</div>
						<div class="show" style="--per: 80%;"><div class="line"></div></div>
					</div><div class="skill">
						<div class="name">python</div>
						<div class="show" style="--per: 90%;"><div class="line"></div></div>
					</div><div class="skill">
						<div class="name">django</div>
						<div class="show" style="--per: 87%;"><div class="line"></div></div>
					</div><div class="skill">
						<div class="name">bootstrap</div>
						<div class="show" style="--per: 95%;"><div class="line"></div></div>
					</div>
				</div>
			</div>
			<div class="interest">
			<h1 class="title">interest</h1>
			<ul>
				<li><i class="fa fa-gamepad" aria-hidden="true"></i>gaming</li>
				<li><i class="fa fa-microphone" aria-hidden="true"></i>sniging</li>
				<li><i class="fa fa-book" aria-hidden="true"></i>reading</li>
				<li><i class="fa fa-cutlery" aria-hidden="true"></i>cooking</li>
			</ul>
		</div>
	</div>
</body>
</html>

templates/about/list.html
{% load i18n %}
<!-- about me -->
<a id="about-me"></a>
<section class="about_me">
	<h1 id="title" class="header">{% trans 'about me' %}</h1>
	{% for about in about_list %}
		<div class="container">
			<div class="image-container">
				<img id="image" src="{{about.pictuer.url}}" alt="{{about.name}}">
			</div>
			<p id="name">{{about.name}}</p>
			<div id="job">{{about.job}}</div>
			<p id="main-text"> 
				{{about.about_my_self}}
			</p>
			<br>
			<div class="btn-random"><a href="{% url 'about:cv' %}">{% trans 'MY_CV' %}</a></div>
		</div>
	{% endfor %}
</section>
<!-- /about me -->

templates/base/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
	<!-- ---------------------------------------------- styles ------------------------------------------ -->
	
	<link rel="stylesheet" href="{% static 'base/assetss/css/main.css' %}">
	{% if LANGUAGE_CODE == 'per' %}
		<link rel="stylesheet" href="{% static 'base/assetss/css/rtl.css' %}">
	{% endif %}
	<!-- ----------------------------------------------------------------------------------------------------- -->
	<!-- swipper  -->
	<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
	<!-- end swipper  -->
	<title>nasir ahmad ahamdy programmer</title>
</head>
<body>
	<!-- The Site Navigation -->
	<nav>
		<div class="left">
			<div class="button-menu">{% trans 'Menu' %}</div>
			<ul>
				<li>
					<a href="{% url 'base:home' %}">{% trans 'Home' %}</a>
				</li>
				<li>
					<a href="{% url 'projects:ProjectList' %}">{% trans 'projects' %}</a>
				</li>
				<li>
					<a href="{% url 'base:home' %}">{% trans 'Skills' %}</a>
				</li>
				<li>
					<a href="{% url 'base:home' %}">{% trans 'about me' %}</a>
				</li>
				<li>
					<a href="{% url 'base:home' %}">{% trans 'contact' %}</a>
				</li>
				<li>
					<a href="#">
						{% trans 'Selecting Language' %}
				    </a>
					<ul>
						<li>
							<a class="nav-link nav-user mr-0 waves-eff" href="/en{{ request.get_full_path|slice:'4:' }}" role="button">
								{% trans 'English' %}
						    </a>	
						</li>
						<li>
							<a class="nav-link nav-user mr-0 waves-eff" href="/pt{{ request.get_full_path|slice:'4:' }}" role="button">
								{% trans 'Portuguese' %}
						    </a>	
						</li>
						<li>
							<a class="nav-link nav-user mr-0 waves-eff" href="/per{{ request.get_full_path|slice:'4:' }}" role="button">
								{% trans 'persion' %}
						    </a>	
						</li>
						<li>
							<a class="nav-link nav-user mr-0 waves-eff" href="/de{{ request.get_full_path|slice:'4:' }}" role="button">
								{% trans 'Deutsch' %}
						    </a>	
						</li>
					</ul>
				</li>
			</ul>
		</div>
		<div class="right">
			<div class="logo" style="background-image: url({% static 'base/assetss/images/per.jpg' %});"></div>
		</div>
	</nav>
	<!-- /nav  -->
	<a id="home"></a>
	<!-- the site header -->
	<div class="header" style="background-image: url({% static 'base/assetss/images/bg.jpg' %});">
		<div class="title">
			<p class="text">{% trans "hello, i'm" %}</p>
			<h1 class="title">{% trans 'nasir ahmad ahmdy.' %}</h1>
			<div class="sub-title">{% trans 'i am the web developer.' %}</div>
		</div>
	</div>
	<!-- /the site header -->
	{% block main %}{% endblock %}
	<!-- the footer -->
	<div class="footer">
		<ul>
			<li>
				<a href="#"><i class="fab fa-facebook"></i></a>
			</li>
			<li>
				<a href="#"><i class="fab fa-instagram"></i></a>
			</li>
			<li>
				<a href="#"><i class="fab fa-whatsapp"></i></a>
			</li>
		</ul>
	</div>
	<!-- /the footer -->
	<!-- ------------------------------------------------- main js ---------------------------------------- -->
	<script src="{% static 'base/assetss/js/script.js' %}"></script>
	<!-- touch slider -->
	<script>
         $(".carousel").owlCarousel({
           margin: 20,
           loop: true,
           autoplay: true,
           autoplayTimeout: 2000,
           autoplayHoverPause: true,
           responsive: {
             0:{
               items:1,
               nav: false
             },
             600:{
               items:2,
               nav: false
             },
             1000:{
               items:4,
               nav: false
             }
           }
         });
      </script>
</body>
</html>

templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% load projects_tags %}

{% block main %}
	<!-- projects -->
	{% last_projects %}

	<!-- skills -->
	{% include 'skills/list.html' %}
	<!-- about me -->
	{% include 'about/list.html' %}
	<!-- contact us -->
	{% include 'contact/list.html' %}
{% endblock %}
{% include 'projects/list.html' %}

templates/contact/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% trans 'Django Email Send' %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />
  </head>

  <body>
    {% block body %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous">
    </script>
  </body>

</html>

templates/contact/contact.html
{% extends 'contact/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h1>{% trans 'Contact Us' %}</h1>
</div>
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
    <button class="btn btn-success my-3" type="submit">{% trans 'Send message' %}</button>
    </form>
</div>
{% endblock %}

templates/contact/contact_list.html
{% extends 'base/base.html' %}
{% block main %}
	{% include 'contact/list.html' %}
{% endblock %}

templates/contact/list.html
{% load i18n %}
<!-- contact us -->
	<a id="contact-us"></a>
	<section class="contact-us">
		<h1 class="title">{% trans 'contact us' %}</h1>
		<p style="text-transform: capitalize;">{% trans 'you can also contact me with nasirahmadahmady0@gmail.com imail.' %}</p>
		<div class="contact">
				<div class="contant-info">
					<h1 class="title">{% trans 'contact info' %}</h1>
					<div class="address">
						<i class="icon ion-location"></i>
						<div class="text">
							<p class="title">{% trans 'address' %}</p>
							<p class="des">{{contact.address}}</p>
						</div>
					</div>
					<div class="phone">
						<i class="icon ion-android-call"></i>
						<div class="text">
							<p class="title">{% trans 'phone' %}</p>
							<p class="des">{{contact.phone_number}}</p>
						</div>
					</div>
					<div class="email">
						<i class="icon ion-email"></i>
						<div class="text">
							<p class="title">{% trans 'email' %}</p>
							<p class="des">{{contact.email}}</p>
						</div>
					</div>
				</div>
			<div class="message">
				<form method="post">{% csrf_token %}
					<h1>{% trans 'message me' %}</h1>
					<div class="name">
						{{ form.name }}
					</div>
					<div class="email">
						{{ form.email }}
					</div>
					<div class="inquiry">
						{{ form.inquiry }}
					</div>
					<div class="your-message">
						{{ form.message }}
					</div>
					<button type="submit">
						{% trans 'send' %}
					</button>
				</form>
			</div>
		</div>
	</section>
	<!-- /contact us -->

templates/contact/success.html
{% extends 'contact/base.html' %}
{% load i18n %}

{% block body %}
<div class="mx-auto my-4 text-center">
    <h1 class="fw-bolder text-success">{% trans 'We sent your message' %}</h1>
    <p class="my-5">{% trans You can send another in the %} <a href="{% url 'base:home' %}">{% trans 'contact page' %}</a></p>
</div>
{% endblock %}

templates/projects/backends_language.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'projects/backend_projects/backend_projects_main.css' %}">
	<title>Backend Projects</title>
</head> 
<body style="background-image: url({% static 'projects/backend_projects/bg.jpg' %});">
	<div class="message-wrapper">
		<div class="left">
			<h1 class="title">oops!</h1>
			<p class="message">we can't show the page you requested In order for the selected project to run on the server</p>
			<p class="maybe">Please download and run the codes from the following address:</p>
			<a href="{{downlaod_link}}" class="button download">Download Projects</a>
			<a href="{% url 'base:home' %}" class="button back">back to home</a>
		</div>
		<div class="right">
			<div class="img" style="background-image: url({% static 'projects/backend_projects/per.png' %})"></div>
		</div>
	</div>
</body>
</html>

templates/projects/list.html
{% load static %}
{% load i18n %}
<!-- projects -->
<section class="projects">
	<a href="{% url 'projects:ProjectList' %}" id="projects"><h1 class="title">{% trans 'projects' %}</h1></a>
	<div class="projects-wrapper">
		{% for project in projec_list %}
			<div class="project"> 
				<div class="img" style="background-image: url('{{project.thumbnail.url}}');"></div>
				<div class="logo" style="background-image: url(
					{% if project.language_type == 'h' %}
						{% static 'base/assetss/images/html_logo.png' %}
					{% elif project.language_type == 'c' %}
						{% static 'base/assetss/images/css_logo.png' %}
					{% elif project.language_type == 'j' %}
						{% static 'base/assetss/images/js_logo.png' %}
					{% elif project.language_type == 'p' %}
						{% static 'base/assetss/images/python_logo.png' %}
					{% elif project.language_type == 'b' %}
						{% static 'base/assetss/images/bootstrap_logo.png' %}
					{% elif project.language_type == 'd' %}
						{% static 'base/assetss/images/django_logo.png' %}
					{% else %}
						{% static 'base/assetss/images/html_logo.png' %}
					{% endif %}
				);
				border: solid #fff 5px;"></div>
				<div class="content">
					<h1 class="title" >{{project.title}}</h1>
					<p class="description">{{project.description|truncatewords:30}}</p>
					<div class="btn-wrapper">
						<a href="{% url 'projects:ProjectDetail' project.slug %}" target="_blank" class='download-btn'>preview</a>
						{% if project.is_private == False %}
						    {% if project.language_type == 'p' or project.language_type == 'd' %}
						       <a href="{% url 'projects:backend_languages' project.slug %}" target="_blank" class='download-btn'>download</a>
						    {% else  %}
						       <a href="{% url 'projects:ProjectDetail' project.slug %}" target="_blank" class='download-btn'>download</a>
						    {% endif %}
						 {% endif %}
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	{% if request.get_full_path == '/' %}
		<a href="{% url 'projects:ProjectList' %}" class="show-more">{% trans 'More Projects' %}</a>
	{% endif %}
	
</section>
<!-- /projects -->